---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: traefik-conf
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "INFO"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [kubernetes]
    [web]
    address = ":8080"
    [acme]
    email = "victor.j.fdez@gmail.com"
    storage = "traefik/acme/account"
    entryPoint = "https"
    dnsProvider = "route53"
    acmeLogging = true
    delayDontCheckDNS = 30 
    onDemand = true
    onHostRule = true
    #caServer = "https://acme-staging.api.letsencrypt.org/directory"
    [[acme.domains]]
    main = "misas.io"
    [consul]
    endpoint = "traefik-consul:8500"
    watch = true
    prefix = "traefik"
